try:
   print(3/0)
except:
   #print('error identified')
   pass
print('completed')